export interface ITFIAddress {
    ID?: number,
    Street1: string,
    Street2: string,
    City: string,
    State: string,
    ZipCode: string,
    County: string,
}

export const USStatesSelectList =[

    {title:'AL',value:'Alabama'},
    {title:'AK',value:'Alaska'},
    {title:'AZ',value:'Arizona'},
    {title:'AR',value:'Arkansas'},
    {title:'CA',value:'California'},
    {title:'CO',value:'Colorado'},
    {title:'CT',value:'Connecticut'},
    {title:'DE',value:'Delaware'},
    {title:'DC',value:'District Of Columbia'},
    {title:'FL',value:'Florida'},
    {title:'GA',value:'Georgia'},
    {title:'HI',value:'Hawaii'},
    {title:'ID',value:'Idaho'},
    {title:'IL',value:'Illinois'},
    {title:'IN',value:'Indiana'},
    {title:'IA',value:'Iowa'},
    {title:'KS',value:'Kansas'},
    {title:'KY',value:'Kentucky'},
    {title:'LA',value:'Louisiana'},
    {title:'ME',value:'Maine'},
    {title:'MD',value:'Maryland'},
    {title:'MA',value:'Massachusetts'},
    {title:'MI',value:'Michigan'},
    {title:'MN',value:'Minnesota'},
    {title:'MS',value:'Mississippi'},
    {title:'MO',value:'Missouri'},
    {title:'MT',value:'Montana'},
    {title:'NE',value:'Nebraska'},
    {title:'NV',value:'Nevada'},
    {title:'NH',value:'New Hampshire'},
    {title:'NJ',value:'New Jersey'},
    {title:'NM',value:'New Mexico'},
    {title:'NY',value:'New York'},
    {title:'NC',value:'North Carolina'},
    {title:'ND',value:'North Dakota'},
    {title:'OH',value:'Ohio'},
    {title:'OK',value:'Oklahoma'},
    {title:'OR',value:'Oregon'},
    {title:'PA',value:'Pennsylvania'},
    {title:'RI',value:'Rhode Island'},
    {title:'SC',value:'South Carolina'},
    {title:'SD',value:'South Dakota'},
    {title:'TN',value:'Tennessee'},
    {title:'TX',value:'Texas'},
    {title:'UT',value:'Utah'},
    {title:'VT',value:'Vermont'},
    {title:'VA',value:'Virginia'},
    {title:'WA',value:'Washington'},
    {title:'WV',value:'West Virginia'},
    {title:'WI',value:'Wisconsin'},
    {title:'WY',value:'Wyoming'},
];
